version: '3.7'

services:
        
        mochi_server:
         build: .
         #image: dockerjjz/mochi_local_version
         ports:
                 - "3811:3838"
                 - "8011:80"
         volumes:
                 - ./seqs_folder:/home/imuser/raw_data/:rw
                 - ./taxa_database/greengenes:/home/imuser/taxa_database/greengenes:rw
                 - ./taxa_database/silva:/home/imuser/taxa_database/silva:rw
                 - ./taxa_database/PR2:/home/imuser/taxa_database/PR2:rw
         container_name: mochi_local_server
         
         deploy:
           resources:
             limits:
               cpus: '0.80'
               memory: 6G
         
         environment:
                 - shiny_port=3811
                 - nginx_port=8011  
